name: Deploy to GitHub Pages

permissions:
  contents: write  
  pull-requests: write
  
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Navigate to frontend folder
        run: cd Frontend/smart-ecommerce-platform

      - name: Install dependencies
        run: npm install
        working-directory: Frontend/smart-ecommerce-platform

      - name: Build Angular project
        run: npm run build --prod
        working-directory: Frontend/smart-ecommerce-platform

      - name: Set up ghpages
        run: npm install angular-cli-ghpages --save-dev

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/smart-ecommerce-platform
