name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: Frontend/smart-ecommerce-platform
      run: npm install

    - name: Build Angular app
      working-directory: Frontend/smart-ecommerce-platform
      run: npm run build -- --configuration=production --base-href "https://dmg0411.github.io/SmartE-CommercePlatform/"

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cd Frontend/smart-ecommerce-platform/dist/smart-ecommerce-platform
        git init
        git remote add origin https://github.com/DMG0411/SmartE-CommercePlatform.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy Angular app to GitHub Pages"
        git push --force origin gh-pages
