name: Deploy Angular App with SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

env:
  SONAR_PROJECT_KEY: SmartE-commercePlatform-Frontend
  SONAR_ORGANIZATION: dmg0411

jobs:
  build-analyze-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Shallow clones should be disabled for a better relevancy of analysis
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: Frontend/smart-ecommerce-platform
      run: npm install

    - name: Run unit tests with coverage
      working-directory: Frontend/smart-ecommerce-platform
      run: npm run test:coverage

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v4.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: Frontend/smart-ecommerce-platform
        args: >
          -Dsonar.organization=dmg0411
          -Dsonar.projectKey=DMG0411_SmartE-CommercePlatform
          -Dsonar.sources=src
          -Dsonar.tests=src
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.coverage.exclusions="**/*.spec.ts,**/main.ts,**/environments/**"

    - name: Build Angular app
      working-directory: Frontend/smart-ecommerce-platform
      run: npm run build -- --configuration=production --base-href "https://dmg0411.github.io/SmartE-CommercePlatform/"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: Frontend/smart-ecommerce-platform/dist/smart-ecommerce-platform
        branch: gh-pages
        clean: true
