name: Build and deploy .NET Core application to Web App SmartE-commercePlatform with API Management Service SmartE-commercePlatformapi-SmartE-commercePlatform

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: SmartE-commercePlatform
  AZURE_WEBAPP_PACKAGE_PATH: SmartE-commercePlatform/publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: DefaultResourceGroup-DEWC
  AZURE_APIM_SERVICENAME: SmartE-commercePlatformapi
  AZURE_APIM_API_ID: SmartE-commercePlatform
  AZURE_APIM_APPSERVICEURL: https://smarte-commerceplatform.azurewebsites.net
  SWASHBULCKLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.0.0  # Update to a version compatible with .NET 6
  API_IMPORT_SPECIFICATION_PATH: SmartE-commercePlatform/publish/swagger.json
  API_IMPORT_DLL: SmartE-commercePlatform/bin/Release/net8.0/SmartE-commercePlatform.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: Backend/SmartE-commercePlatform.sln

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install .NET SDK 5.0
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=linux-x64&os=ubuntu.22.04
        sudo dpkg -i dotnet-sdk-5.0.0-linux-x64.deb

    - name: Restore dependencies
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}

    - name: Build the project
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run tests
      run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build

    - name: Install Swashbuckle CLI .NET Global Tool
      run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBULCKLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

    - name: Verify Swagger CLI Installation
      run: dotnet tool list -g

    - name: Generate OpenAPI Specification Document
      run: |
        # Ensure correct paths for DLL and output
        swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "${{ env.API_IMPORT_VERSION }}"

    - name: Publish application
      run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.SmartE_commercePlatform_C7C9 }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SmartE_commercePlatformapi_SPN }}

    - name: Import API into Azure API Management
      run: |
        az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" --service-name "${{ env.AZURE_APIM_SERVICENAME }}" --api-id "${{ env.AZURE_APIM_API_ID }}" --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" --specification-format OpenApi --subscription-required false

    - name: Logout from Azure
      run: az logout
